name: Java CI with Gradle # как называется Workflow

on: [push, pull_request] # когда срабатывает (на push и pull_request)

jobs: # какие задачи делаем
  build: # сборка

    runs-on: ubuntu-latest # на какой ОС запускаем

    steps: # какие шаги выполняем
      - uses: actions/checkout@v2 # выкачиваем репо
      - name: Set up JDK 11
        uses: actions/setup-java@v2 # устанавливаем JDK
        with:
          java-version: 11 # версия для установки
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build # запускаем Gradle (вместо build можно использовать test)